"""Pad the five carousel slides onto one canvas so the deck is a single fixed size.

LinkedIn renders a document post at ONE aspect ratio for every page. The five slides are
generated by three different scripts with different natural shapes — the bracket is wide,
the text slides are tall — so without this step the carousel jumps size between pages.

Padding, not resizing: each slide is scaled to fit inside the canvas with its aspect intact,
then centred on the deck's background colour. Because that colour is the slides' own
background, the padding is invisible and every page ends up exactly CANVAS pixels.

4:5 portrait is the canvas because it is the tallest shape LinkedIn shows in full, so the
text slides get the most screen. It costs the bracket nothing: on a phone the bracket is
limited by the screen's WIDTH either way, and a wider canvas would only shrink slides 1, 4
and 5.

Run after 14, 16 and 17. Those scripts write their raw figures into FIGURES/_raw (gitignored);
this step reads from there and writes the FINISHED carousel_*.png into FIGURES, plus the PDF. So
there is one figure per slide in the tracked folder — no raw/padded pair sitting side by side.
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).parent
FIGURES = ROOT / "reports" / "figures"
RAW = FIGURES / "_raw"

CANVAS = (1600, 2000)
BACKGROUND = (17, 26, 43)

# Minimum clearance on all four edges, as a fraction of the SHORT side. Every page is fitted
# inside CANVAS minus this inset, so nothing can ever start at an edge — the slides are built by
# three different scripts and each was setting its own margins, so some pages ran right to the
# border while others floated in the middle. A page whose shape differs more from 4:5 simply
# gets more than the minimum; it never gets less.
SAFE_MARGIN = 0.045

SLIDES = [
    "carousel_1_hook.png",
    "carousel_2_bracket.png",
    "carousel_3_odds_vs_reality.png",
    "carousel_4_calibration.png",
    "carousel_5_close.png",
]


def normalise(name):
    source = Image.open(RAW / name).convert("RGB")
    inset = round(min(CANVAS) * SAFE_MARGIN)
    safe = (CANVAS[0] - 2 * inset, CANVAS[1] - 2 * inset)
    scale = min(safe[0] / source.width, safe[1] / source.height)
    fitted = source.resize((round(source.width * scale), round(source.height * scale)),
                           Image.LANCZOS)

    canvas = Image.new("RGB", CANVAS, BACKGROUND)
    canvas.paste(fitted, ((CANVAS[0] - fitted.width) // 2,
                          (CANVAS[1] - fitted.height) // 2))

    # The finished slide keeps the raw file's name — there is no raw copy in FIGURES to clash with,
    # since the raw lives in _raw. So the deck is just carousel_1..5.png, no suffix.
    out = FIGURES / name
    canvas.save(out)
    print(f"saved {out}  ({source.width}x{source.height} -> {CANVAS[0]}x{CANVAS[1]})")
    return canvas


pages = [normalise(slide) for slide in SLIDES]

# LinkedIn takes a carousel as ONE PDF, one page per slide — not five images. Every page is the
# same pixel size by construction above, which is what stops the deck resizing as you swipe.
# Quality 88 keeps the whole deck comfortably under the ~3 MB where the feed starts to soften
# images; the type here is flat colour on flat background, so JPEG artefacts have nothing to
# grab onto.
pdf = FIGURES / "wc2026_report_card_carousel.pdf"
pages[0].save(pdf, save_all=True, append_images=pages[1:], resolution=150.0, quality=88)
print(f"\nsaved {pdf}  ({len(pages)} pages, {pdf.stat().st_size / 1_000_000:.2f} MB)")
